development:
  adapter: postgresql
  encoding: unicode
  database: slovencina_development
  username: databaser
  password: multipass
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: slovencina_test
  username: databaser
  password: multipass
  host: localhost
  pool: 5
  timeout: 5000